package:
  name: conda-tracker
  version: {{ GIT_DESCRIBE_TAG }}.{{ GIT_BUILD_STR }}

source:
  git_url: ../

build:
  number: 0
  entry_points:
    - conda-tracker = conda_tracker.cli:cli

requirements:
  build:
    - python
    - setuptools
  run:
    - click
    - GitPython
    - PyGithub

test:
  requires:
    - pytest
    - pytest-xdist
  commands:
    - which conda-tracker  # [unix]
    - where conda-tracker  # [win]
    - conda tracker --help
    - py.test tests -n 4

  imports:
    - conda_tracker
    - conda_tracker.library

  source_files:
    - tests

about:
  home: https://github.com/conda/conda-tracker
  license: BSD 3-clause
